// <auto-generated />
using System;
using Day15_EFCore.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Day15EFCore.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20221114032329_AddTableStudentCourses")]
    partial class AddTableStudentCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Day15_EFCore.DataBase.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("VarChar(200)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", "dbo");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("DoB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("VarChar(20)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("VarChar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students", "dbo");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.StudentAddress", b =>
                {
                    b.Property<int>("StudentAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentAddressId"));

                    b.Property<string>("Address1")
                        .HasColumnType("VarChar(200)");

                    b.Property<string>("Address2")
                        .HasColumnType("VarChar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("StudentAddressId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentAddresses", "dbo");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.StudentCourses", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CoursesCourseId");

                    b.ToTable("StudentCourses", "dbo");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VarChar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("VarChar(100)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers", "dbo");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Courses", b =>
                {
                    b.HasOne("Day15_EFCore.DataBase.Teacher", "Teachers")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.StudentAddress", b =>
                {
                    b.HasOne("Day15_EFCore.DataBase.Student", "Student")
                        .WithOne("StudentAddress")
                        .HasForeignKey("Day15_EFCore.DataBase.StudentAddress", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.StudentCourses", b =>
                {
                    b.HasOne("Day15_EFCore.DataBase.Courses", "Courses")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Day15_EFCore.DataBase.Student", "Students")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Courses", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Student", b =>
                {
                    b.Navigation("StudentAddress")
                        .IsRequired();

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("Day15_EFCore.DataBase.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
